### ISSUE TITLE
Table view broken

### ISSUE THREAD

**Issue by bricel** [Gizra/productivity#262]
Not sure if it's related to GH patch.
![image](https://cloud.githubusercontent.com/assets/165644/14314732/a5904436-fc16-11e5-90dd-2ee261bbf351.png)
a

**Comment by nader77** [comment]
Yes I tried to fix some of the JavaScript errors on `serve`, I'll fix right away in #259

**Comment by bricel** [comment]
@nader77 might be related to https://github.com/Gizra/productivity/pull/250/files

**Comment by nader77** [comment]
@bricel Could you refresh or logout and in again ?
I can't reproduce, Even on the live app:
<img width="1077" alt="gizra_-_tracking_table" src="https://cloud.githubusercontent.com/assets/7369740/14314902/5eff7f9e-fbfa-11e5-870b-18c0234cc9cf.png">

**Comment by bricel** [comment]
Still get the same error, also after login logout,  and clear cache. 
I get this error in the logs (for each project):

LOCATION	http://live-productivity.pantheonsite.io/api/tracking?year=2016&month=4
REFERRER	http://productivity.gizra.com/?code=9dd2c0c826ddda44649f
MESSAGE	Notice: Undefined index: projectName in RestfulFormatterTrackingCalendar->arrangeByDate() (line 167 of /srv/bindings/3e77f9bfa0174cd0ad701add26044179/code/profiles/productivity/modules/custom/productivity_restful/plugins/formatter/tracking_calendar/RestfulFormatterTrackingCalendar.class.php).

**Comment by bricel** [comment]
and this one too:

LOCATION	http://live-productivity.pantheonsite.io/api/tracking?year=2016&month=4
REFERRER	http://productivity.gizra.com/?code=9dd2c0c826ddda44649f
MESSAGE	Notice: Undefined index: employee in RestfulFormatterTrackingCalendar->arrangeByDate() (line 139 of /srv/bindings/3e77f9bfa0174cd0ad701add26044179/code/profiles/productivity/modules/custom/productivity_restful/plugins/formatter/tracking_calendar/RestfulFormatterTrackingCalendar.class.php).

**Comment by nader77** [comment]
@bricel I can't reproduce live or locally, Which account are you using ?

**Comment by nader77** [comment]
@bricel It's a fix of permission in Drupal `7.43` that when a user is not authorizied to view other user's profiles, It won't even send the data to the entity reference field:
![people___gizra_productivity](https://cloud.githubusercontent.com/assets/7369740/14487701/83f5aad4-0164-11e6-9270-79f62af4d98c.jpg)

When I ticked that box the error was gone, Because your account have only `Authenticated user` permission, As a quick fix I have changed your account to administrator, I think this table should not be visible to `Authenticated user` in the application anyway, I'm going to add some permissions to this page on the app, What do you think ?

**Comment by bricel** [comment]
Sounds right, Thanks!
